
import 'package:preschool_learning_app/models/e_alphabet_image_audio.dart';

class EAlphabetLists {
  static List<EAlphabetImageAudio> alphabets = <EAlphabetImageAudio>[
    EAlphabetImageAudio(
      'A',
      'assets/alphabet/capital/a.webp',
      'assets/alphabet/audio/a.mp3',
    ),
    EAlphabetImageAudio(
      'B',
      'assets/alphabet/capital/b.webp',
      'assets/alphabet/audio/b.mp3',
    ),
    EAlphabetImageAudio(
      'C',
      'assets/alphabet/capital/c.webp',
      'assets/alphabet/audio/c.mp3',
    ),
    EAlphabetImageAudio(
      'D',
      'assets/alphabet/capital/d.webp',
      'assets/alphabet/audio/d.mp3',
    ),
    EAlphabetImageAudio(
      'E',
      'assets/alphabet/capital/e.webp',
      'assets/alphabet/audio/e.mp3',
    ),
    EAlphabetImageAudio(
      'F',
      'assets/alphabet/capital/f.webp',
      'assets/alphabet/audio/f.mp3',
    ),
    EAlphabetImageAudio(
      'G',
      'assets/alphabet/capital/g.webp',
      'assets/alphabet/audio/g.mp3',
    ),
    EAlphabetImageAudio(
      'H',
      'assets/alphabet/capital/h.webp',
      'assets/alphabet/audio/h.mp3',
    ),
    EAlphabetImageAudio(
      'I',
      'assets/alphabet/capital/i.webp',
      'assets/alphabet/audio/i.mp3',
    ),
    EAlphabetImageAudio(
      'J',
      'assets/alphabet/capital/j.webp',
      'assets/alphabet/audio/j.mp3',
    ),
    EAlphabetImageAudio(
      'K',
      'assets/alphabet/capital/k.webp',
      'assets/alphabet/audio/k.mp3',
    ),
    EAlphabetImageAudio(
      'L',
      'assets/alphabet/capital/l.webp',
      'assets/alphabet/audio/l.mp3',
    ),
    EAlphabetImageAudio(
      'M',
      'assets/alphabet/capital/m.webp',
      'assets/alphabet/audio/m.mp3',
    ),
    EAlphabetImageAudio(
      'N',
      'assets/alphabet/capital/n.webp',
      'assets/alphabet/audio/n.mp3',
    ),
    EAlphabetImageAudio(
      'O',
      'assets/alphabet/capital/o.webp',
      'assets/alphabet/audio/o.mp3',
    ),
    EAlphabetImageAudio(
      'P',
      'assets/alphabet/capital/p.webp',
      'assets/alphabet/audio/p.mp3',
    ),
    EAlphabetImageAudio(
      'Q',
      'assets/alphabet/capital/q.webp',
      'assets/alphabet/audio/q.mp3',
    ),
    EAlphabetImageAudio(
      'R',
      'assets/alphabet/capital/r.webp',
      'assets/alphabet/audio/r.mp3',
    ),
    EAlphabetImageAudio(
      'S',
      'assets/alphabet/capital/s.webp',
      'assets/alphabet/audio/s.mp3',
    ),
    EAlphabetImageAudio(
      'T',
      'assets/alphabet/capital/t.webp',
      'assets/alphabet/audio/t.mp3',
    ),
    EAlphabetImageAudio(
      'U',
      'assets/alphabet/capital/u.webp',
      'assets/alphabet/audio/u.mp3',
    ),
    EAlphabetImageAudio(
      'V',
      'assets/alphabet/capital/v.webp',
      'assets/alphabet/audio/v.mp3',
    ),
    EAlphabetImageAudio(
      'W',
      'assets/alphabet/capital/w.webp',
      'assets/alphabet/audio/w.mp3',
    ),
    EAlphabetImageAudio(
      'X',
      'assets/alphabet/capital/x.webp',
      'assets/alphabet/audio/x.mp3',
    ),
    EAlphabetImageAudio(
      'Y',
      'assets/alphabet/capital/y.webp',
      'assets/alphabet/audio/y.mp3',
    ),
    EAlphabetImageAudio(
        'Z', 'assets/alphabet/capital/z.webp', 'assets/alphabet/audio/z.mp3')
  ];
}
