import 'package:preschool_learning_app/models/lesson_content.dart';

class LessonContentList {
  static List<LessonContentImageAudio> alphabets = <LessonContentImageAudio>[
    LessonContentImageAudio(
      'A',
      'assets/alphabet/capital/a.webp',
      'assets/alphabet/audio/a.mp3',
    ),
    LessonContentImageAudio(
      'B',
      'assets/alphabet/capital/b.webp',
      'assets/alphabet/audio/b.mp3',
    ),
    LessonContentImageAudio(
      'C',
      'assets/alphabet/capital/c.webp',
      'assets/alphabet/audio/c.mp3',
    ),
    LessonContentImageAudio(
      'D',
      'assets/alphabet/capital/d.webp',
      'assets/alphabet/audio/d.mp3',
    ),
    LessonContentImageAudio(
      'E',
      'assets/alphabet/capital/e.webp',
      'assets/alphabet/audio/e.mp3',
    ),
    LessonContentImageAudio(
      'F',
      'assets/alphabet/capital/f.webp',
      'assets/alphabet/audio/f.mp3',
    ),
    LessonContentImageAudio(
      'G',
      'assets/alphabet/capital/g.webp',
      'assets/alphabet/audio/g.mp3',
    ),
    LessonContentImageAudio(
      'H',
      'assets/alphabet/capital/h.webp',
      'assets/alphabet/audio/h.mp3',
    ),
    LessonContentImageAudio(
      'I',
      'assets/alphabet/capital/i.webp',
      'assets/alphabet/audio/i.mp3',
    ),
    LessonContentImageAudio(
      'J',
      'assets/alphabet/capital/j.webp',
      'assets/alphabet/audio/j.mp3',
    ),
    LessonContentImageAudio(
      'K',
      'assets/alphabet/capital/k.webp',
      'assets/alphabet/audio/k.mp3',
    ),
    LessonContentImageAudio(
      'L',
      'assets/alphabet/capital/l.webp',
      'assets/alphabet/audio/l.mp3',
    ),
    LessonContentImageAudio(
      'M',
      'assets/alphabet/capital/m.webp',
      'assets/alphabet/audio/m.mp3',
    ),
    LessonContentImageAudio(
      'N',
      'assets/alphabet/capital/n.webp',
      'assets/alphabet/audio/n.mp3',
    ),
    LessonContentImageAudio(
      'O',
      'assets/alphabet/capital/o.webp',
      'assets/alphabet/audio/o.mp3',
    ),
    LessonContentImageAudio(
      'P',
      'assets/alphabet/capital/p.webp',
      'assets/alphabet/audio/p.mp3',
    ),
    LessonContentImageAudio(
      'Q',
      'assets/alphabet/capital/q.webp',
      'assets/alphabet/audio/q.mp3',
    ),
    LessonContentImageAudio(
      'R',
      'assets/alphabet/capital/r.webp',
      'assets/alphabet/audio/r.mp3',
    ),
    LessonContentImageAudio(
      'S',
      'assets/alphabet/capital/s.webp',
      'assets/alphabet/audio/s.mp3',
    ),
    LessonContentImageAudio(
      'T',
      'assets/alphabet/capital/t.webp',
      'assets/alphabet/audio/t.mp3',
    ),
    LessonContentImageAudio(
      'U',
      'assets/alphabet/capital/u.webp',
      'assets/alphabet/audio/u.mp3',
    ),
    LessonContentImageAudio(
      'V',
      'assets/alphabet/capital/v.webp',
      'assets/alphabet/audio/v.mp3',
    ),
    LessonContentImageAudio(
      'W',
      'assets/alphabet/capital/w.webp',
      'assets/alphabet/audio/w.mp3',
    ),
    LessonContentImageAudio(
      'X',
      'assets/alphabet/capital/x.webp',
      'assets/alphabet/audio/x.mp3',
    ),
    LessonContentImageAudio(
      'Y',
      'assets/alphabet/capital/y.webp',
      'assets/alphabet/audio/y.mp3',
    ),
    LessonContentImageAudio(
        'Z', 'assets/alphabet/capital/z.webp', 'assets/alphabet/audio/z.mp3')
  ];

  static List<LessonContentImageAudio> fruits = <LessonContentImageAudio>[
    LessonContentImageAudio(
      'Apple',
      'assets/Fruits/apple.jpg',
      'assets/Fruits/audio/grapes.mp3',
    ),
    LessonContentImageAudio(
      'Banana',
      'assets/Fruits/banana.jpg',
      'assets/Fruits/audio/banana.mp3',
    ),
    LessonContentImageAudio(
      'Blueberry',
      'assets/Fruits/blue berry.png',
      'assets/Fruits/audio/banana.mp3',
    ),
    LessonContentImageAudio(
      'Grapes',
      'assets/Fruits/grapes.png',
      'assets/Fruits/audio/grapes.mp3',
    ),
    LessonContentImageAudio(
      'Guava',
      'assets/Fruits/guava.jpg',
      'assets/Fruits/audio/guava.mp3',
    ),
    LessonContentImageAudio(
      'Jack fruits',
      'assets/Fruits/jack fruits.jpg',
      'assets/Fruits/audio/jack fruit.mp3',
    ),
    LessonContentImageAudio(
      'Lemon',
      'assets/Fruits/lemon.jpg',
      'assets/Fruits/audio/lemon.mp3',
    ),
    LessonContentImageAudio(
      'Lime',
      'assets/Fruits/lime.jfif',
      'assets/Fruits/audio/banana.mp3',
    ),
    LessonContentImageAudio(
      'Mango',
      'assets/Fruits/mango.jpg',
      'assets/Fruits/audio/mango.mp3',
    ),
    LessonContentImageAudio(
      'Orange',
      'assets/Fruits/orange.jpg',
      'assets/Fruits/audio/orange.mp3',
    ),
    LessonContentImageAudio(
      'Papaya',
      'assets/Fruits/papaya.jpg',
      'assets/Fruits/audio/papaya.mp3',
    ),
    LessonContentImageAudio(
      'Pear',
      'assets/Fruits/pear.jpg',
      'assets/Fruits/audio/banana.mp3',
    ),
    LessonContentImageAudio(
      'Pine Apple',
      'assets/Fruits/pine apple.jpg',
      'assets/Fruits/audio/pineapple.mp3',
    ),
    LessonContentImageAudio(
      'Straw berry',
      'assets/Fruits/strawberry.jpg',
      'assets/Fruits/audio/banana.mp3',
    ),
    LessonContentImageAudio(
      'Water melon',
      'assets/Fruits/water melon.jpg',
      'assets/Fruits/audio/watermelon.mp3',
    ),
    LessonContentImageAudio(
      'wood Apple',
      'assets/Fruits/wood apple.jpg',
      'assets/Fruits/audio/woodapple.mp3',
    ),
  ];

// tamil alphabets
  static List<LessonContentImageAudio> TamilAlphabets =
      <LessonContentImageAudio>[
    LessonContentImageAudio(
      'அ',
      'assets/tamil/tamil letter/1.png',
      'assets/tamil/audio/அ.mp3',
    ),
    LessonContentImageAudio(
      'ஆ',
      'assets/tamil/tamil letter/2.png',
      'assets/tamil/audio/ஆ.mp3',
    ),
    LessonContentImageAudio(
      'இ',
      'assets/tamil/tamil letter/3.png',
      'assets/tamil/audio/இ.mp3',
    ),
    LessonContentImageAudio(
      'ஈ',
      'assets/tamil/tamil letter/4.png',
      'assets/tamil/audio/ஈ.mp3',
    ),
    LessonContentImageAudio(
      'உ',
      'assets/tamil/tamil letter/5.png',
      'assets/tamil/audio/உ.mp3',
    ),
    LessonContentImageAudio(
      'ஊ',
      'assets/tamil/tamil letter/6.png',
      'assets/tamil/audio/ஊ.mp3',
    ),
    LessonContentImageAudio(
      'எ',
      'assets/tamil/tamil letter/7.png',
      'assets/tamil/audio/எ.mp3',
    ),
    LessonContentImageAudio(
      'ஏ',
      'assets/tamil/tamil letter/8.jfif',
      'assets/tamil/audio/ஏ.mp3',
    ),
    LessonContentImageAudio(
      'ஐ',
      'assets/tamil/tamil letter/9.jpg',
      'assets/tamil/audio/ஐ.mp3',
    ),
    LessonContentImageAudio(
      'ஒ',
      'assets/tamil/tamil letter/10.jfif',
      'assets/tamil/audio/ஒ.mp3',
    ),
    LessonContentImageAudio(
      'ஓ',
      'assets/tamil/tamil letter/11.png',
      'assets/tamil/audio/ஓ.mp3',
    ),
    LessonContentImageAudio(
      'ஔ',
      'assets/tamil/tamil letter/12.png',
      'assets/tamil/audio/ஔ.mp3',
    ),
  ];

  static List<LessonContentImageAudio> Numbers = <LessonContentImageAudio>[
    LessonContentImageAudio(
      '0',
      'assets/number/0.webp',
      'assets/number/audio/0.mp3',
    ),
    LessonContentImageAudio(
      '1',
      'assets/number/1.webp',
      'assets/number/audio/1.mp3',
    ),
    LessonContentImageAudio(
      '2',
      'assets/number/2.webp',
      'assets/number/audio/2.mp3',
    ),
    LessonContentImageAudio(
      '3',
      'assets/number/3.webp',
      'assets/number/audio/3.mp3',
    ),
    LessonContentImageAudio(
      '4',
      'assets/number/4.webp',
      'assets/number/audio/4.mp3',
    ),
    LessonContentImageAudio(
      '5',
      'assets/number/5.webp',
      'assets/number/audio/5.mp3',
    ),
    LessonContentImageAudio(
      '6',
      'assets/number/6.webp',
      'assets/number/audio/6.mp3',
    ),
    LessonContentImageAudio(
      '7',
      'assets/number/7.webp',
      'assets/number/audio/7.mp3',
    ),
    LessonContentImageAudio(
      '8',
      'assets/number/8.webp',
      'assets/number/audio/8.mp3',
    ),
    LessonContentImageAudio(
      '9',
      'assets/number/9.webp',
      'assets/number/audio/9.mp3',
    ),
    LessonContentImageAudio(
      '10',
      'assets/number/10.webp',
      'assets/number/audio/10.mp3',
    ),
  ];

  static List<LessonContentImageAudio> Colors = <LessonContentImageAudio>[
    LessonContentImageAudio(
      'black',
      'assets/Colours/black.webp',
      'assets/Colours/audio/black.mp3',
    ),
    LessonContentImageAudio(
      'white',
      'assets/Colours/white.webp',
      'assets/Colours/audio/white.mp3',
    ),
    LessonContentImageAudio(
      'brown',
      'assets/Colours/brown.webp',
      'assets/Colours/audio/brown.mp3',
    ),
    LessonContentImageAudio(
      'green',
      'assets/Colours/green.webp',
      'assets/Colours/audio/green.mp3',
    ),
    LessonContentImageAudio(
      'orange',
      'assets/Colours/orange.webp',
      'assets/Colours/audio/orange.mp3',
    ),
    LessonContentImageAudio(
      'pink',
      'assets/Colours/pink.webp',
      'assets/Colours/audio/pink.mp3',
    ),
    LessonContentImageAudio(
      'purple',
      'assets/Colours/purple.webp',
      'assets/Colours/audio/purple.mp3',
    ),
    LessonContentImageAudio(
      'red',
      'assets/Colours/red.webp',
      'assets/Colours/audio/red.mp3',
    ),
    LessonContentImageAudio(
      'blue',
      'assets/Colours/blue.webp',
      'assets/Colours/audio/blue.mp3',
    ),
    LessonContentImageAudio(
      'yellow',
      'assets/Colours/yellow.webp',
      'assets/Colours/audio/yellow.mp3',
    ),
  ];
}
